#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: La Cave DIY

# Short bio or description (displayed in the header)
description: Site de DIY

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

https_redirect: false

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: lacavediy@gmail.com
  facebook: https://facebook.com/lacavediy
  flickr:
  github: https://github.com/lacavediy
  instagram: https://www.instagram.com/lacavediy
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: lacavediy
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: channel/UCOLynmtCEg_4Vd2yMTa2ZNQ
  googleplus: # anything in your profile username that comes after plus.google.com/

seo:
  author: "La Cave DIY"
  authorGPlus: "https://plus.google.com/107372593286776964898"
  facebookAdmin: 558346437
  twitterType: "summary_large_image"
  twitterSite: "@lacavediy"
  twitterCreator: "@lacavediy"

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: la-cave-diy

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-106958300-2

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://lacavediy.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
